//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_mst
    {
        public int id { get; set; }
        public string category_id { get; set; }
        public string code { get; set; }
        public string value { get; set; }
        public string comment { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
