//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class prison_mst
    {
        public int id { get; set; }
        public string ma_dang_ky { get; set; }
        public string ma_trai_giam { get; set; }
        public Nullable<System.DateTime> ngay_thang_nam_sinh { get; set; }
        public string ho_va_ten { get; set; }
        public string ten_goi_khac { get; set; }
        public string gioi_tinh { get; set; }
        public string que_quan { get; set; }
        public string noi_dktt { get; set; }
        public string toi_danh { get; set; }
        public Nullable<System.DateTime> ngay_bat { get; set; }
        public string an_phat { get; set; }
        public Nullable<System.DateTime> ngay_nhap_trai { get; set; }
        public string phan_loai_quan_che { get; set; }
        public Nullable<System.DateTime> ngay_dua_vao_dien_quan_che { get; set; }
        public string doi_hien_tai { get; set; }
        public string buong_so { get; set; }
        public string phan_trai { get; set; }
        public string danh_muc { get; set; }
        public string danh_muc_1 { get; set; }
        public string pham_vi_hoat_dong { get; set; }
        public string bieu_hien_hoat_dong_hien_hanh { get; set; }
        public string bien_phap_nghiep_vu { get; set; }
        public string bien_phap_ky_luat { get; set; }
        public Nullable<System.DateTime> ngay_dua_ra { get; set; }
        public string ly_do_dua_ra { get; set; }
        public string ton_giao { get; set; }
        public string dan_toc { get; set; }
        public string quoc_tich { get; set; }
        public string trinh_do_hoc_van { get; set; }
        public string ngoai_ngu { get; set; }
        public string ten_cha { get; set; }
        public string ten_me { get; set; }
        public string ten_vo_chong { get; set; }
        public string tien_an { get; set; }
        public string tien_su { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string nguoi_tao { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
        public string nguoi_cap_nhat { get; set; }
        public string tom_tat_toi_danh { get; set; }
    }
}
